[tool.poetry]
name = "easyplot"
version = "0.1.0"
description = ""
authors = ["acse-dx121 <dx121@ic.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
